### ISSUE TITLE
Where to find the actual .plasmaoid-file?

### ISSUE THREAD

**Issue by xWolpertinger01** [MrGovindDubey/Plasmoids#3]
Installation through plasma doesn't work properly so I wanted to install it via local file (.plasmaoid) but I can't seem to find it anywhere in the repo, please help me

**Comment by MrGovindDubey** [comment]
You don't need to look for a .plasmoid file. Instead, simply fork or clone the repository and copy the com.mrgovinddubey.discord folder to the following location:

/home/$USER/.local/share/plasma/plasmoids/

This should allow you to install and use the plasmoid locally.

**Comment by MrGovindDubey** [comment]
Open a terminal and run the following commands:

```bash
git clone https://github.com/MrGovindDubey/Plasmoids.git
cp -r Plasmoids/com.mrgovinddubey.discord ~/.local/share/plasma/plasmoids/

This will clone the repository and copy the com.mrgovinddubey.discord folder to the appropriate location for Plasma.

**Comment by MrGovindDubey** [comment]
Open a terminal and run the following commands:

```bash
git clone https://github.com/MrGovindDubey/Plasmoids.git
cp -r Plasmoids/com.mrgovinddubey.discord ~/.local/share/plasma/plasmoids/
```
This will clone the repository and copy the com.mrgovinddubey.discord folder to the appropriate location for Plasma.
